export const types = {
  CREATE_PLAYLIST: `CREATE_PLAYLIST`,
  START_RECENTLY_ADDED: 'START_RECENTLY_ADDED',
  SUCCESS_RECENTLY_ADDED: 'SUCCESS_RECENTLY_ADDED',
  FAILURE_RECENTLY_ADDED: 'FAILURE_RECENTLY_ADDED',
  START_SELECTED_SONG: 'START_SELECTED_SONG',
  SUCCESS_SELECTED_SONG: 'SUCCESS_SELECTED_SONG',
  FAILURE_SELECTED_SONG: 'FAILURE_SELECTED_SONG',
  SET_PLAYING_TRUE:'SET_PLAYING_TRUE',
  SET_PLAYING_FALSE:'SET_PLAYING_FALSE'
}




export const ERROR = 'error';
