export const types = {
  CREATE_PLAYLIST: `CREATE_PLAYLIST`,
  START_RECENTLY_ADDED: 'START_RECENTLY_ADDED',
  SUCCESS_RECENTLY_ADDED: 'SUCCESS_RECENTLY_ADDED',
  FAILURE_RECENTLY_ADDED: 'FAILURE_RECENTLY_ADDED',
  SET_ISPLAYING: 'SET_ISPLAYING',
  SET_VOLUME: 'SET_VOLUME',
  TOGGLE_MUTE: 'TOGGLE_MUTE',
  START_SET_AUDIO_TRACK: 'START_SET_AUDIO_TRACK',
  SUCCESS_SET_AUDIO_TRACK: 'SUCCESS_SET_AUDIO_TRACK',
  FAILURE_SET_AUDIO_TRACK: 'FAILURE_SET_AUDIO_TRACK',
  SET_PLAY_FROM_LIST: 'SET_PLAY_FROM_LIST',
  SET_SELECTED_PLAYlIST: 'SET_SELECTED_PLAYlIST',

}




export const ERROR = 'error';
